export const CREATE_CART = "CREATE_CART";
export const CREATE_CART_FAIL = "CREATE_CART_FAIL";
export const CREATE_CART_SUCCESS = "CREATE_CART_SUCCESS";

export const FETCH_CART = "FETCH_CART";
export const FETCH_CART_FAIL = "FETCH_CART_FAIL";
export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";
