export const CREATE_ITEM = "CREATE_ITEM";
export const CREATE_ITEM_FAIL = "CREATE_ITEM_FAIL";
export const CREATE_ITEM_SUCCESS = "CREATE_ITEM_SUCCESS";

export const UPDATE_ITEM = "UPDATE_ITEM";
export const UPDATE_ITEM_FAIL = "UPDATE_ITEM_FAIL";
export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS";

export const DELETE_ITEM = "DELETE_ITEM";
export const DELETE_ITEM_FAIL = "DELETE_ITEM_FAIL";
export const DELETE_ITEM_SUCCESS = "DELETED_ITEM_SUCCESS";
