export const CREATE_ORDER = "CREATE_ORDER";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";

export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";

export const FETCH_ORDER = "FETCH_ORDER";
export const FETCH_ORDER_FAIL = "FETCH_ORDER_FAIL";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";

export const UPDATE_ORDER = "UPDATE_ORDER";
export const UPDATE_ORDER_FAIL = "UPDATE_ORDER_FAIL";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";

export const DELETE_ORDER = "DELETE_ORDER";
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
