export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const UPDATE_USER_CREDENTIALS = "UPDATE_USER_CREDENTIALS";
export const UPDATE_USER_CREDENTIALS_FAIL = "UPDATE_USER_CREDENTIALS_FAIL";
export const UPDATE_USER_CREDENTIALS_SUCCESS = "UPDATE_USER_CREDENTIALS_SUCCESS";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
