export const ADDRESS_START = "ADDRESS_START";
export const ADDRESS_SUCCESS = "ADDRESS_SUCCESS";
export const ADDRESS_FAIL = "ADDRESS_FAIL";

export const FETCH_ADDRESSES_START = "FETCH_ADDRESS_START";
export const FETCH_ADDRESSES_SUCCESS = "FETCH_ADDRESS_SUCCESS";
export const FETCH_ADDRESSES_FAIL = "FETCH_ADDRESS_FAIL";

export const UPDATE_ADDRESS_START = "UPDATE_ADDRESS_START";
export const UPDATE_ADDRESS_SUCCESS = "UPDATE_ADDRESS_SUCCESS";
export const UPDATE_ADDRESS_FAIL = "UPDATE_ADDRESS_FAIL";